image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
  only:
    - master
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker build -t registry.gitlab.com/xerethars/hvz_api .
    - docker push registry.gitlab.com/xerethars/hvz_api
  after_script:
    - docker logout ${CI_REGISTRY}
  stage: build
  tags:
    - docker